### ISSUE TITLE
[BUG] displaySystem IPython

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#184]
the code from

The Source Objects and their Fields

gives bad output when plotting inline. output is fine with Qt5.

![image](https://user-images.githubusercontent.com/47384012/60218876-f07d1880-9870-11e9-8d4d-0fe2dd7e1d08.png)

**Comment by lucasgcb** [comment]
This is actually a problem with how Inline mode works on Spyder's IPython. It will happen with any multi-axis pyplot where the user attempts to `show()` before both plots have data in them, so it is not a problem with our library per se. 

However we are already equipped to handle this :)

Since you cannot update what is already shown in IPython's inline mode, if you do `Collection.displaySystem()` with the  `suppress=True` kwarg and execute `pyplot.show()` at the end you will get both plots.

For the matter, the last hotfix fixed a bigger problem which was halting script execution entirely, making displaySystem unusable without the supppress kwarg outside of [matplotlib's interactive mode](https://matplotlib.org/faq/usage_faq.html#what-is-interactive-mode).
