### ISSUE TITLE
[REQUEST] magnet class improvement

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#188]
TRANSCRIPT FROM ALEX:

here is a brief example

example class:

![image](https://user-images.githubusercontent.com/47384012/60508211-4b2bcf80-9cca-11e9-800b-76c311fbed23.png)

You define a new magnet like this:
 
![image](https://user-images.githubusercontent.com/47384012/60508244-60086300-9cca-11e9-9eae-9c1a06f7de2e.png)

with the __repr__ method there is a useful representation of the object (rather than direct reference to the object:
 
![image](https://user-images.githubusercontent.com/47384012/60508256-6991cb00-9cca-11e9-95be-5e13a7a8b97d.png)

Without, it looks like this:
 
![image](https://user-images.githubusercontent.com/47384012/60508266-6e567f00-9cca-11e9-9d6b-39b499e9a2d1.png)

With specific IPython display methods it could e.g. look like this in Jupyter:

![image](https://user-images.githubusercontent.com/47384012/60508279-77dfe700-9cca-11e9-9a59-8a0d8a41b826.png)
![image](https://user-images.githubusercontent.com/47384012/60508290-7c0c0480-9cca-11e9-85e6-9a19502ffcfd.png)

**Comment by OrtnerMichael** [comment]
Dear Alex,

Thank you for the feedback!!
We understand that you address two issues:

1. Is there a particular reason why you would structure the classes as you have shown in "example class". Meaning that you would introduce getter and setter methods ? It is our understanding that this is not standard procedure in Python because you can always access all attributes of all objects anytime.

2. We like the idea that there is a string output instead of reference to the object. But we are not sure if there is sufficient demand to justify adding a feature that can easily be mimicked by any user. We think this is just for console use of the library - is there a special use-case for you that we are not aware of? We would like to know why you want this.

**Comment by Alexboiboi** [comment]
Hi @OrtnerMichael, thanks for taking the time for this request. 

1. It was never my intention to restructure the class you have implemented in your library. I just needed a base class to show an example for the  `__repr__` method. The getter and setter methods were just here because I was experimenting on these methods on my side.

2. For use in the jupyter notebook, it is sometimes just convenient to see the magnet parameters at one glance to verify if all paremeters are defined correctly just by calling the variable. In this case it is just an unecessary feature but nice to have. ;)

Alex-

**Comment by OrtnerMichael** [comment]
We get it. Thank you for the feedback !!!

We will think about this some more - keep the Issue open and probably add it in the future.
