### ISSUE TITLE
Download & Win Install Doku

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#219]
How to just download and move to site-packages for pip-free use under windows

**Comment by lucasgcb** [comment]
Why would you want to go pip-free? If internet connection is your concern, `pip` should be able to quickly install locally placed packages to a given environment.

**Comment by OrtnerMichael** [comment]
Hm I have a partner who is using windows and not anaconda. He didn't want to install pip which is also non-trivial under windows.

He just wanted to download the package and copy it into the lib-site packages folder ... dunno if that actually worked for him - but maybe we can bring out a brief guideline how to install like that

**Comment by lucasgcb** [comment]
`pip` is actually included by default since Python 3.4, if he doesn't have it in his environment it is likely he does not have the correct Python version to work the library (currently 3.6 minimum because of latest numpy). 

What he needs to do is add his preferred Python interpreter to [PATH](https://en.wikipedia.org/wiki/PATH_(variable)) so he can call it through his terminal to use pip. In the Python 3.7 installer this is offered as an option.

Alternatively, he can run the following script:

```python

import subprocess
import sys

def install(package):
    subprocess.call([sys.executable, "-m", "pip", "install", package])
	
install("magpylib")

```

This will ask the current Python Interpreter to call pip and install magpylib without needing the command line.

### The long road
In the case **he does have an updated Python** and simply doesn't want to pip for some reason, he would have to deal with installing numpy/scipy and matplotlib and their own dependencies manually as well since `pip` is in charge of identifyingl, downloading, and correctly placing them all. You will also see that doing this manually is the reason why pip is included by default.

At this point he may consider getting [other scientific distributions](https://www.scipy.org/install.html#scientific-python-distributions-recommended) which come with these dependencies pre-installed; then it really literally is just copying the [magpylib folder](https://github.com/magpylib/magpylib/tree/master/magpylib) into site-packages.

**Comment by OrtnerMichael** [comment]
thanks for this long and detailed answer - i'll have to test this but im quite busy at the moment - end of september things will hopefully calm down then i will address this in detail.

**Comment by OrtnerMichael** [comment]
yeah i think we leave it as it is
