### ISSUE TITLE
simulation: particles movement

### ISSUE THREAD

**Issue by incafox** [magpylib/magpylib#220]
**Describe the feature you'd like**

Hi, is posible to use magpylib to simulate movement of particles around a magnet/electromagnet?
pls im looking for a software that can let me simulate something like that.

**Comment by OrtnerMichael** [comment]
hi incafox,

thanks for your inquiry. Please let me know in detail what you you need.

My guess is that you want to calculate forces on particles in real time that are either charged or magnetized. If this is the case you can use magpylib to calculate the global magnetic field (of an electromagnet or of a permanent magnet), and use a simple formula (electromotive force law or force on a magnetic moment) to calculate the actual force on each particle which depends on position, orientation and velocity and which will give you the respective acceleration. magpylib can be useful for this because the B-field calculation is very fast so this can be done in real time.

sounds like an interesting example to add :)

sincerely,
Michael

**Comment by incafox** [comment]
hi, thanks for answer me, this is exactly what i'm looking for:
I need simulate 6 electromagnets and apply to this a control system in order to move a microparticle ubicated on the center, just like this picture: 

https://www.fz-juelich.de/SharedDocs/Bilder/ICS/ICS-8/EN/Expertise/Instrumentation/02-MolecularAndCellBiology/MagnTwistingCytometry.jpg?__blob=poster

It is about a device called magnetic tweezer.

So, as you said, i need to calculate the total force applied on the central microparticle, and with this simulate the movement of that particle and then apply some control system for the position.  
Is possible simulate that kind of enviroment with magpylib?.

**Comment by OrtnerMichael** [comment]
Whats the magnetic field amplitude that you would like to achieve in your application ?

My guess is that you want to reach high amplitudes O(1T) for which you require a soft-magnetic core in your electromagnets (just as in the sketch). In this case magpylib cannot be applied as there is no analytical solution when material the magnetization depends on the field (one must incorporate magnetization curves). This requires more sophisticated methods like FEM.

There are several FEM toolboxes out there that are easy to use (like ANSYS Maxwell or COMSOL) and have implemented solvers for magnetostatic fields.

sincerely,
Michael

**Comment by incafox** [comment]
Thanks for the answer
