### ISSUE TITLE
[BUG] - ANG=[] list is ignored in magpylib.vector.getBv_magnet

### ISSUE THREAD

**Issue by rzhvsk** [magpylib/magpylib#247]
It could be me, but i could not make ANG=[] work in magpylib.vector.getBv_magnet; angle values are being ignored.

Take "Using magpylib.vector" chapter from documentation and add a list of (M=2) arrays (length of N each) with angles (e. g. 30 and 90 since documentation says [deg]);
make every np.tile "bigger" (MAG = np.tile(mag,(M*N,1)) and so on.)
"loop" POSm to have two identical sets of coordinates in a row (btw why? one set should be enough but it won't work that way);

draw plt of Bv (3 lines for 3 components) and observe identical parts of a graph no matter of ANG contents (0/5/30/15/90) instead of two slightly different parts of a graph.

**Screenshots**
N from documentation was changed to 10, angles are 0 and 30.
![2020-07-22](https://user-images.githubusercontent.com/55632016/88201608-55f83000-cc50-11ea-8804-b9b7870c36e5.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 64-bit]
 - IDE: [VS Code]

```
pip freeze output:
cycler==0.10.0
kiwisolver==1.2.0
magpylib==2.3.0b0
matplotlib==3.2.2
numpy==1.19.0
pyparsing==2.4.7
python-dateutil==2.8.1
six==1.15.0
```
Could anyone check if i am mistaken somewhere? Mayve i misunderstood how this should work; as i intend to use it with a sphere i managed to bypass this with rotating MAG vector but it is kinda annoying and not applicable to 'box'.

**Comment by rzhvsk** [comment]
And if i don't enlarge POSm and all other arrays by two times ANG=[] is still ignored; i get one graph this way.

An example in the documentation would be nice :(
![2020-07-22 (1)](https://user-images.githubusercontent.com/55632016/88203106-79bc7580-cc52-11ea-94de-0033bbab3f4e.png)

**Comment by lucasgcb** [comment]
Hi, thanks for making this report.

Before we go further into this, would you kindly share the code you've run that returns this behavior? 
It will help us narrowing down your problem.

**Comment by rzhvsk** [comment]
This is code from my first screenshot and please don't judge.
`
import magpylib as magpy
import matplotlib.pyplot as plt
import numpy as np

N = 10
M = 2

mag = np.array([0,0,1000.])
dim  = np.array([2,2,2.])       
poso = np.array([0,0,4.])      
posm = np.array([0,0,0])        

xMag = np.linspace(-10,10,N)
ang1 = np.tile(np.array([0]), (N,1))
ang2 = np.tile(np.array([30]), (N,1))

MAG = np.tile(mag,(M*N,1))
DIM = np.tile(dim,(M*N,1))
POSo = np.tile(poso, (M*N,1))
POSm = np.c_[xMag,np.zeros((N,2))]
POSm2 = np.concatenate((POSm, POSm), axis = 0)

Bv = magpy.vector.getBv_magnet('box',MAG,DIM,POSo,POSm, ANG=[ang1, ang2]) #also tried with ANCH, still ignores

fig = plt.figure(figsize=(5,5))
ax1 = fig.add_subplot(111)

ax1.plot(Bv)
plt.show()
`

**Comment by OrtnerMichael** [comment]
Dear @rzhvsk 

Ty for reporting this  and sorry for the late reply.

There are actually 2 mistakes here:

1. The arguments of getBv_magnet are ('type', MAG, DIM, **POSm, POSo**,...). POSm and POSo are reverted! This was changed in the last version, but was not updated in the doku.
2. When applying a rotation all inputs ANG=[ang1,ang2,...], AX=[ax1,ax2,...] and ANCH=[anch1,anch2,...] are required to give these rotations a meaning. In addition, for an input vector with N evaluations, the format of each ang1, ang2,... must be a np.array of all the angles - So shape(ang1) should return (N,) and not (N,1) !!!, the shapes of ax and anch must then be (N,3) respectively.

In your code ang1 and ang2 are only of length N while they should define subsequent rotations first by ang1 then by ang2 with respective lengths N*M.

Also, since you dont give AX and ANCH arguments that part is ignored. This should not be the case - there should be an error msg - so we'll track this down.

sincerely,
Michael

**Comment by rzhvsk** [comment]
Thank you for the response,

i checked out new examples, everything works. Still, concerning mistake #1, in example codes (05_vectorjoystick1d) POSo and POSm are not inverted :)

I will close this thread now.
