### ISSUE TITLE
Issue: Displaying wrong magnetization direction

### ISSUE THREAD

**Issue by pribossek** [magpylib/magpylib#273]
In the current version of MagPylLib3, the magnetization direction is not being rotated when the magnet is rotated. 
The getB however seems to return the correct field, so this seems to be an issue of only the `display` method.

`mag=Box(mag=[1000,0,0],pos=[1,1,1],dim=[5,5,3])
mag.rotate_from_angax(45,"z")
mag.display(direc=True)`

![grafik](https://user-images.githubusercontent.com/22050435/111786189-cf1e5480-88bd-11eb-8202-04a80f3c2196.png)

**Comment by OrtnerMichael** [comment]
The problem should be fixed with the latest commit in magpylib3_develeopment!
Thank you for pointing it out.

Here is a sneak preview that also demonstrates the new path functionality :)

![image](https://user-images.githubusercontent.com/47384012/111863941-a13d1c80-895e-11eb-82aa-2eccdf91c295.png)

@pribossek Please test if this also solves your problem and then close the issue.

**Comment by pribossek** [comment]
Thanks, it works as i should!
