### ISSUE TITLE
TASK - CI/CD of documentation

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#295]
- [x] setup read the docs for automatic doc upload
- [x] how to preserve the old documentations in read the docs

**Comment by lucasgcb** [comment]
We have to check if we would like to to maintain the [magpylib3_development ](https://github.com/magpylib/magpylib/tree/magpylib3_development) branch after 3.0 release or decide if we will merge into [development](https://github.com/magpylib/magpylib/tree/development), so we can make the appropriate adjustments on ReadTheDocs.

Currently the `development` branch has v2.3.0. For structure sake pertaining the cd/ci pipeline I think it's better we merge the release candidate for v3 from `magpylib3_development` into `development`; the source code for v2.3.0 is [already tagged](https://github.com/magpylib/magpylib/releases/tag/2.3.0-beta) in master so there doesn't seem to be any losses.

**Comment by OrtnerMichael** [comment]
I agree but there are many conflicts.

can I just delete **development** and rename **magpylib3_development** instead of making a mega merge ? or will this also ruin the cd/ci pipeline?

**Comment by lucasgcb** [comment]
> I agree but there are many conflicts.
> 
> can I just delete **development** and rename **magpylib3_development** instead of making a mega merge ? or will this also ruin the cd/ci pipeline?
It could work, but there are git merge options for situations like these.

One way to fix this is first merging "just" the head of the `development` branch into `magpylib3_development`, in order to clear the conflicts without making changes and preserve history; And then merging `magpylib3_development` into `development`. This is done with the ["ours" merge strategy option](https://www.atlassian.com/git/tutorials/using-branches/merge-strategy#:~:text=The%20Ours%20strategy%20operates%20on,history%20of%20similar%20feature%20branches.) on the command line git, which would preserve the history without requiring us to delete `development`.

I can create a PR soonish addressing this; just wanted to make sure if we were going to perform any merge at all.

**Comment by laikh** [comment]
sounds good to me, please go ahead.

Lucas Gabriel Coliado Bandeira ***@***.***> schrieb am So.,
2. Mai 2021, 10:32:

**Comment by lucasgcb** [comment]
v2.3.0-beta should be [here](https://magpylib.readthedocs.io/en/2.3.0-beta/) permanently, and can be accessed from the side bar by clicking at the bottom.
![image](https://user-images.githubusercontent.com/7332704/117003516-53d10080-acbb-11eb-912f-059d8d05f66a.png)

**Comment by OrtnerMichael** [comment]
nice - this is another issue that can be closed then

**Comment by lucasgcb** [comment]
> We have to check if we would like to maintain the [magpylib3_development ](https://github.com/magpylib/magpylib/tree/magpylib3_development) branch after 3.0 release or decide if we will merge into [development](https://github.com/magpylib/magpylib/tree/development), so we can make the appropriate adjustments on ReadTheDocs.
> 
> Currently the `development` branch has v2.3.0. For structure sake pertaining the cd/ci pipeline I think it's better we merge the release candidate for v3 from `magpylib3_development` into `development`; the source code for v2.3.0 is [already tagged](https://github.com/magpylib/magpylib/releases/tag/2.3.0-beta) in master so there doesn't seem to be any losses.

Reopening this issue to document the merge/overwrite (magpylib3_development -> development)  process.

**Comment by lucasgcb** [comment]
Reference for the commit overwriting the development head: https://github.com/magpylib/magpylib/commit/7473f6b4e37f722b809c58b5d8afe15dc979b4d0
