### ISSUE TITLE
Commercial-use warning

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#308]
SAL management wants a 1-time warning that Magpylib is not intended for commercial use.

This should be a simple printout after the first import - **and then it should not ever appear again !**

how to do this ?

**Comment by lucasgcb** [comment]
We have to define what "again" means, because since this is a software library rather than application software, the user can run parts of the scripts several times or across machines. There's no real user flow or closed-source visual interface to tie warnings to.

So we have two (poor) options:

1- Print the notice during installation (_depends on pip or conda not suppressing it, which they already do_).
2- Attempt to run code with side effects that print the notice every time the user runs `import magpylib`, then records this event in a python variable or [environment variable](https://en.wikipedia.org/wiki/Environment_variable).

Keeping in mind that such prints have little legal significance if the License that accompanies the source code is not proper ( which is being discussed in #302 ). Taken our open source nature, nothing would keep users from removing this feature themselves, unless the License is customized and demands this to happen in order for them to legally use the software.

**Comment by OrtnerMichael** [comment]
1. There will never be a possibility to check if someone uses the library 'illegaly'.
2. Companies will generally not use software illegally to avoid going into legal battles, specifically when there is no real money involved - we are asking for peanuts :) - so we hope that they will contact us, and we will try to find company partners who work in the field who might be interested in the technology.
3. There should be no stupid msg that bugs users all the time.
4. However, it would be nice, to make users aware of the legal issues in a non-threatening way - also to refer them to our documentation and to the developers.

So I think there should be a simple msg, the first time after installation when the import statement is compiled. Something like

**ONE TIME MSG**
_Thank you for using Magpylib._
_Documentation at https://magpylib.readthedocs.io/en/latest/._
_Magpylib is developed and maintained with the support of **Silicon Austria Labs**._
_Magpylib will always be free of use for all non-commercial purposes (AGPL license)._
_For any questions and commercial licenses please contact us at magpylib@gmail.com._

It should be possible to have a statement in magpylib/__init__ like
```
if Config.ONE_TIME_MSG:
    print(msg)
    Config.ONE_TIME_MSG =False
    os.save(magpylib/_lib/config.py)
```
but probably this solution will have write issues if Magpylib does not have admin rights.

**Comment by OrtnerMichael** [comment]
its a marketing issue :)
