### ISSUE TITLE
[BUG] - the calculation of magnetic field for a coil

### ISSUE THREAD

**Issue by caimingxue** [magpylib/magpylib#381]
When the position of the coil or circular is on the z axis([0, 0, z]), and the observer point is also on the z axis([0, 0, data]), if rotate the coil with anchor = observer point along x axis or y axis. The amplitude of magnetic field(np.linalg.norm(field)) will not be constant when the coil rotates. However, if the position of the coil or observer point is not on the z axis, the result is correct. The following code  can be used to check this bug.  By the way, how to show the current direction in the coil or circular
import magpylib as magpy
import numpy as np
import time
magnet = magpy.Collection()
for z in np.linspace(8,12,20):
    winding = magpy.current.Circular(
        current = 1,
        diameter = 5,  
        position = (0,0,z))
    magnet += winding
observe = [0, 0, 2] #[0.1, 0, 2]
for i in range(30):
    angle = -10 * i
    magnet.rotate_from_angax(angle, 'x', anchor=observe)
    sensor = magpy.Sensor(position=observe)
    # sensor.rotate_from_angax(angle, 'z', anchor=(0, 0, 0))
    # print(np.linalg.norm(sensor.position))
    field = magnet.getB(sensor)
    norm = np.linalg.norm(field)
    print(angle, field, norm)
    # print(norm * np.sin(np.pi/6), norm * np.cos(np.pi/6))
    magnet.display(markers=[sensor.position], show_direction=True)
    time.sleep(1)

**Comment by OrtnerMichael** [comment]
hi @caimingxue

yes this is a bug :), thank you for pointing it out !
Here the problem is broken down to its core (@peter-leitner check this out):

```
import numpy as np
import magpylib as magpy

source = magpy.current.Circular(current=1, diameter=5, position=(0,0,3))
observe = np.array((0,0,2))

for _ in range(5):
    source.rotate_from_angax(11, 'x', anchor=observe)
    B = source.getB(observe)
    print(np.linalg.norm(B))
```

which creates this strange output

```
0.20116521042168908
0.6273522855301199
0.2823139358216281
0.28231393582162795
0.2097581377843564
```

**Why did this happen ?**
You are evaluating the field at a numerical instability (on the axis of the Circular). This is also discussed in #374 . When you rotate the source about the anchor point, the rotation creates minor offsets (e.g. 1e-14) from the perfect axis, and when that happens the field implementation returns wrong results.

**How to solve this ?**
You can avoid this problem by creating a small (e.g. 1e-8) offset from the center axis. Its not nice but the best we can offer right now.

```
import numpy as np
import magpylib as magpy

source = magpy.current.Circular(current=1, diameter=5, position=(0,0,3))
observe = np.array((0,0,2))

for _ in range(5):
    source.rotate_from_angax(11, 'x', anchor=observe)
    B = source.getB(observe + .0000000123)
    print(np.linalg.norm(B))
```

this creates this stable output

```
0.20116521123137748
0.20116521098745171
0.20116521072273671
0.20116521044695945
0.20116521017025363
```

We currently work on eliminating these instabilities - they will be gone with version 4.

**Comment by caimingxue** [comment]
Thanks for your reply, the issue can be closed.
