### ISSUE TITLE
Computation of magnetic gradient

### ISSUE THREAD

**Issue by caimingxue** [magpylib/magpylib#500]
Hi, does the new version of the magpylib supply the computation about magnetic gradient? Thanks

**Comment by OrtnerMichael** [comment]
hi @caimingxue 

No, we have not implemented gradient fields, mostly for the reason that you can easily compute them using finite differences.

sincerely,
michael

**Comment by OrtnerMichael** [comment]
@caimingxue 

I also wanted to mention ... when you compute gradient field from FE data, then you are always in trouble with finite differences because the #FE data is not smooth:

![image](https://user-images.githubusercontent.com/47384012/159644963-8a1afbc1-c1e3-4ad2-b3d6-f8968a22e95a.png)

However, the Magpylib fields are always completely smooth, down to the numerical precision level. So you can use Magpylib with finite difference without worry ... while you have to be very careful with FEM when you do that.

Can I ask what is your application ?
