### ISSUE TITLE
Disabling vector union?

### ISSUE THREAD

**Issue by DBvdHeijden** [magpylib/magpylib#521]
Hi! Am currently working with some code that's basically a wrapper for magpylib. I am trying to generate a rather complicated design by minimising some cost function, and am basically throwing random geometries in the mix and optimising them. The problem is that due to the vector union, the optimisation algorithm keeps stacking geometries to generate the strongest magnetic field.

Would it be possible to somehow disable the vector union, and instead of summing the vectors summing them and dividing over the number of vectors present? Am currently trying to write some sort of crude object intersection code but failing horribly as I'm not really a coder haha.

Any help would be very much appreciated!

**Comment by OrtnerMichael** [comment]
hi @DBvdHeijden 

That is unfortunately not possible, because it would require that we check internally if objects overlap and the compute the field response for intersection-shapes that we do not have available. In principle you have two options:

1. Write an object intersection code yourself, as you already pointed out
2. Choose relative coordinates that make intersection impossible as it is described by this figure

![image](https://user-images.githubusercontent.com/47384012/163366354-bcfb3043-3940-4652-8c02-feabd96c9cf6.png)

in this paper

https://ieeexplore.ieee.org/abstract/document/7438423

**Comment by DBvdHeijden** [comment]
Ah okay, that is unfortunate haha - thank you for the quick response though!
