### ISSUE TITLE
Bad display of magnetization

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#571]
### Magpylib version

4.x (Latest)

### What happened?

The magnetization vector is displayed badly when the rotation is exactly 90°. the code below produces the following pictures

![image](https://user-images.githubusercontent.com/47384012/211774607-d9b6d77c-0785-4924-bf12-cc681f86d847.png)

![image](https://user-images.githubusercontent.com/47384012/211774754-83c66954-9ed1-46c8-aa91-193ea300785b.png)

This is the bug from discussion #570 - the field computation is ok

### Code example

```Python
import numpy as np
import magpylib as magpy

a = magpy.magnet.CylinderSegment(
    magnetization=(0, 0, 1000),
    dimension=(1, 2, 1, 0, 360),
    position=(3, 25, 0),
    )
b = magpy.magnet.CylinderSegment(
    magnetization=(0, 0, -1000),
    dimension=(1, 2, 1, 0, 360),
    position=(-3, 25, 0),
    )

angs = np.linspace(0,360,25)
a.rotate_from_angax(angs, 'x', (0,0,0))
b.rotate_from_angax(angs, 'x', (0,0,0))

magpy.show(a, b, style_path_frames=1, style_path_show=False)
```

**Comment by Alexboiboi** [comment]
- I cannot reproduce the bug here but this is an issue introduced by #430 which had the side effect of creating the wrong flip in some cases.

```python
import magpylib as magpy
from scipy.spatial.transform import Rotation as R
mag = [0, 0, 1000]
c1 = magpy.magnet.Cuboid(mag, (1,1,1))
c1.orientation = R.from_euler('x', 90, degrees = True)
c2 = c1.copy().move((1.5,0,0))
c2.orientation = R.from_euler('x', 95, degrees = True)

v1 = [[0, 0, 0],[0, -1, 0]]
v2 = [[0, 0, 0],[.1, -1, 0]]
l1 = magpy.current.Line(vertices=v1, current=1).move((0,0,2))
l2 = l1.copy(vertices=v2).move((2,0,0))

magpy.show(c1, c2, l1, l2)
```

All arrows should point in the negative y-direction.

With the main branch it produces:
![image](https://user-images.githubusercontent.com/29252289/211871325-4585811f-eaa6-4ded-92cc-e9ae25a0f029.png)


With the fix branch at https://github.com/magpylib/magpylib/tree/fix-mag-direction
![image](https://user-images.githubusercontent.com/29252289/211871743-70711a17-9514-4714-879e-9b9e54e57282.png)

@OrtnerMichael, can you try out the fix branch and check if the issue is still present?

**Comment by OrtnerMichael** [comment]
Yes this fixes the problem !

![image](https://user-images.githubusercontent.com/47384012/211925318-f5fc43e9-1961-4c84-966f-4048bb56ec4d.png)

🥇
