### ISSUE TITLE
showlegend in plotly

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#650]
I think we have talked about this before:

The plotly legend is sometimes very annoying because it takes up a lot of space. Especially when using `show_context` and multiple columns.

The problemis easily fixed by disabling it - but it requires a figure return ..

```python
# some magpylib code

fig = magpy.show(........, return_fig=True, backend='plotly')
fig.update_layout(showlegend=False)
fig.show()
```

and is very annoying. And how does this work with `show_context` ?

Can we not simply have `showlegend` as kwarg to enable//disbale the legend ?

**Comment by OrtnerMichael** [comment]
There could also be a kwarg `legend_format` with options `none`, `short` (displays no id e.g.), `full`

**Comment by Alexboiboi** [comment]
Hi @OrtnerMichael,

I agree that there should be a more obvious way to disable the legend. This may be even more relevant when working with demagnetization code with many objects.

There is however a hidden feature for the plotly backend, already implemented a long time ago. The layout argument in the `show` function also supports underscore magic, so you could do `magpy.show(..., layout_showlegend, layout_title_text="mytitle", ...)`. For `pyvista` and  `matplotlib` you can use `legend_max_items=0`. It has never been documented because I was not sure I wanted to make this public.

A cleaner approach would be to have something compatible with all backends. The thing is that some arguments needs to be passed to the `figure/canvas` constructor and other to the  internal backend specific`show` command (e.g. plt.show(...))

We could still use the underscore magic to some extent:

`magpy.show(..., backend="plotly", canvas_layout_title_text="My title", show_renderer="json")`

`magpy.show(..., backend="matplotlib", canvas_dpi=80, canvas_figsize=(12,9))`
or maybe
`magpy.show(..., backend="matplotlib", canvas_kwargs=dict(dpi=80, figsize=(12,9))`

`magpy.show(..., backend="pyvista", canvas_window_size= (500, 300), show_jupyter_backend="panel" ) # jupyter_backend is now deprecated, it is just for the example

What do you think?

**Comment by Alexboiboi** [comment]
@OrtnerMichael 

In a new [branch](https://github.com/magpylib/magpylib/tree/show_and_fig_kwargs) I implemented the following, in the same vein as the style magic:

### `fig` and `show` kwargs
- kwargs with `fig` prefix are forwarded to the figure constructor (`Figure` for mpl and plotly, `Plotter` for pyvista)
- kwargs with `show` prefix are forwarded to the `show` call (for all backends)
- if `fig` or `show` are prefixed with a backend name, the kwargs will only be forwarded to the specific backend.

Here an example below with increasing order of precedence:
```python
import magpylib as magpy

c = magpy.magnet.Cuboid((0, 0, 1000), (1, 1, 1))
c.show(
    fig=dict(layout_title_text="fig"),
    fig_layout_title_text="fig_layout",
    plotly_fig=dict(layout_title_text="plotly_fig"),
    plotly_fig_layout_title_text="plotly_fig_layout",
    backend="matplotlib",
)
```

### `legend` magic (to be done yet)

I propose to have besides the `display.style` or `display.animation` properties to have the `display.legend` properties (also in defaults).

- `legend_show=True`, `legend_maxitems=20` (to avoid to have too many entries and freeze the view - e.g. demag meshing)

**Comment by Alexboiboi** [comment]
For the legend there is also the possibility to introduce it at the object level as `style.legend.show`, which I actually prefer. The advantage is, that you can turn off specific traces at will. In the `show` call it 'd make no difference to the previous solution (besides the syntax).

```python
magpy.show(..., style_legend_show=False) # hides all legends
```

@OrtnerMichael better?

**Comment by OrtnerMichael** [comment]
Handing over kwargs to fig with "fig-magic" is a great idea ! 

Handing over to specific backends eludes me a bit in terms of usefulness.

The individual legend style option I find very nice - not sure if I will turn on/off individual traces in the future tho :).
