### ISSUE TITLE
Documentation Version

### ISSUE THREAD

**Issue by purepani** [magpylib/magpylib#729]
### Magpylib version

4.x (Latest)

### What happened?

Currently, the documentation is linked to version 5.0, which doesn't seem to be released yet. I am currently using the latest released version, and was thinking it would be better to link to the latest release version instead

**Comment by OrtnerMichael** [comment]
hi @purepani 

thanks for pointing this out. Its a bit of an annoying problem because it would require to have a separate branch (main-dev or main-docs) or to make a separate release for every doc change.

not sure how to handle this ... its a problem because we are currently caught in-between the versions.

we'll try to figure this one out.

br michael

**Comment by OrtnerMichael** [comment]
will be fixed with upcoming release
